name: Posts Updater
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: git setting
        run: |
          git config --local user.email "nowvilla.physi.311@gmail.com"
          git config --local user.name "Tomoki-i"
      - run: php rss.php
      - name: git commit
        run: |
          git add README.md
          git commit -m "update posts"
          git push origin master
